add_newline = false
format = """
$cmd_duration $directory$git_branch
$character"""
[fill]
symbol = '-'
style = 'fg:bright-black'
[character]
success_symbol = "[ ](bold fg:green)"
error_symbol = "[ ](bold fg:red)"
[package]
disabled = true
[git_branch]
style = "bg:surface"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = " 󰜥 [](bold fg:blue)[$symbol $branch(:$remote_branch)](fg:black bg:blue)[ ](bold fg:blue)"
[git_commit]
commit_hash_length = 4
tag_symbol = " "
[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold red)"
[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 "
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)](green)'
renamed = " ✍️ "
deleted = " 🗑 "
[hostname]
ssh_only = false
format =  "[•$hostname](bg:blue bold fg:black)[](bold fg:blue)"
trim_at = ".companyname.com"
disabled = true
[line_break]
disabled = false
[memory_usage]
disabled = true
[time]
disabled = true
[username]
style_user = "bold bg:blue fg:black"
style_root = "red bold"
format = "[](bold fg:blue)[$user]($style)"
disabled = true
[directory]
home_symbol = " "
read_only = "  "
style = "bg:white fg:black"
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:white)[󰉋 → $path]($style)[](bold fg:white)'
[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "
[cmd_duration]
min_time = 500 # Only shows up if a command actually takes time, making the shell speedier
format = '[](bold fg:yellow)[󰪢 $duration](bold bg:yellow fg:black)[](bold fg:yellow)'
