add_newline = false
scan_timeout = 5

format = """
$username$hostname $directory$git_branch$git_status$git_state$cmd_duration
$character"""

[character]
success_symbol = "[❯ ](bold bright-green)"
error_symbol = "[❯ ](bold bright-red)"

[username]
style_user = "bold bright-green"
style_root = "bold bright-red"
format = "[$user]($style)"
show_always = true
disabled = false

[hostname]
ssh_only = false
format = "[@$hostname](bold bright-green):"
trim_at = ""
disabled = false

[directory]
style = "bold bright-blue"
format = "[$path]($style) "
truncation_length = 4
truncation_symbol = ".../"
read_only = " [RO]"
read_only_style = "bold bright-red"

[git_branch]
style = "bold bright-cyan"
symbol = "git:"
format = "[($symbol$branch)]($style) "
truncation_length = 15
truncation_symbol = "..."

[git_status]
style = "bold bright-yellow"
format = "([\\[$all_status$ahead_behind\\]]($style) )"
conflicted = "~"
ahead = ">"
behind = "<"
diverged = "<>"
untracked = "?"
stashed = "*"
modified = "!"
staged = "+"
renamed = "R"
deleted = "-"

[git_state]
style = "bold bright-red"
format = "([\\[$state$progress_current/$progress_total\\]]($style) )"
cherry_pick = "CHERRY"
rebase = "REBASE"
merge = "MERGE"

[cmd_duration]
style = "bold bright-black"
format = "[$duration]($style)"
min_time = 500

[package]
disabled = true

[memory_usage]
disabled = true

[time]
disabled = true

[line_break]
disabled = false
